--[[--
Booklore Plugin Version Information

Auto-generated by generate-version.sh
DO NOT EDIT THIS FILE MANUALLY

@module koplugin.BookloreSync.version
--]]--

return {
    version = "0.0.0-dev+96073c1",
    version_type = "development",
    git_commit = "96073c1",
    build_date = "2026-02-11T07:52:24Z",
}
